//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbCVEntities : DbContext
    {
        public dbCVEntities()
            : base("name=dbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Deneyimler> Tbl_Deneyimler { get; set; }
        public virtual DbSet<Tbl_Egitim> Tbl_Egitim { get; set; }
        public virtual DbSet<Tbl_İletişim> Tbl_İletişim { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_Sertifika> Tbl_Sertifika { get; set; }
        public virtual DbSet<Tbl_Yetenek> Tbl_Yetenek { get; set; }
        public virtual DbSet<tbl_Hobi> tbl_Hobi { get; set; }
        public virtual DbSet<tbl_SosyalMedya> tbl_SosyalMedya { get; set; }
        public virtual DbSet<tblhakkında> tblhakkında { get; set; }
    }
}
